### ISSUE TITLE
request: encoder with button suport (software debounce needed)

### ISSUE THREAD

**Issue by Ryder17z** [mathertel/RotaryEncoder#13]
Title.

**Comment by FelixHauser** [comment]
I second that. Given that the library works so nicely with the rotary part of the encoder, I just makes sense that it could also support the button, with debouncing included. It would be a large plus.

**Comment by mathertel** [comment]
In my appliances I have often multiple buttons but only one rotary encoder.
I suggest you use the [OneButton library](https://github.com/mathertel/OneButton) for all button inputs and the [RotaryEncoder library](https://github.com/mathertel/RotaryEncoder) for the turning events.
(By combining both libraries the code size will increase in scenarios with multiple buttons)

**Comment by FelixHauser** [comment]
Hi there, 
Thanks for your response. I forked the library and added the bounce functionality for the push button. I literally just sent the push request less than 2 minutes ago. There are no conflicts at all. Users won't have to update the code if they update the library.

**Comment by mathertel** [comment]
But code size will increase for everybody.

**Comment by Ryder17z** [comment]
> But code size will increase for everybody.

I'd argue it's worth it, because I haven't seen this particular encoder without the pushbutton.
