### ISSUE TITLE
Skips a step on direction change

### ISSUE THREAD

**Issue by ilium007** [mathertel/RotaryEncoder#19]
The library works fine in either direction with a Bourns PEC-12R rotary encoder except when changing direction. When changing direction it takes another click on the encoder to register an increase or decrease.

**Comment by ilium007** [comment]
Just worked out, it only does it when running via the inverter with Schmitt-trigger inputs that I use in my designs - 74HC14N

**Comment by nythil** [comment]
Interesting! I also had the library skip steps when changing direction. I'm using it with a 100PPR manual pulse generator. It has 6 terminals including both positive and inverted A & B outputs. The library skipped a step when connected to positive A & B outputs, but the problem disappeared when inverted outputs were used. Still, IMO it's a bug, the library should handle both cases equally.

**Comment by mathertel** [comment]
This may be caused by the fact that the version < 1.5.0 only reported a new value on state 3 (not on state 0)
What is the state value, when the encoder is in a latch position ?

Please check with the new parameter on initialization.

**Comment by ilium007** [comment]
Sorry, why was the issue closed?

**Comment by mathertel** [comment]
I did a lot of testing during implementing the new version and never saw this behavior. Please re-test with new version and maybe you can add more information for the root cause. Feel free to send me a pull request.

**Comment by ilium007** [comment]
New version works perfectly for me now. Thanks!

**Comment by ilium007** [comment]
> This may be caused by the fact that the version < 1.5.0 only reported a new value on state 3 (not on state 0)
> What is the state value, when the encoder is in a latch position ?
> 
> Please check with the new parameter on initialization.

This was the reason it failed for me.
