### ISSUE TITLE
AcceleratedRotator example seems to be wrong

### ISSUE THREAD

**Issue by Danixu** [mathertel/RotaryEncoder#24]
Hello,

I've tried the AcceleratedRotator.ino example becase I want to use it on a project I'm doing, and I've noticed that is not working.

The variable lastMovementDirection is not updated, so the acceleration will never trigger.

Best regards.

**Comment by giupo** [comment]
Same here, it's enough to add the following statement ad by the end of the loop

```C++
lastMovementDirection = currentDirection
```
