### ISSUE TITLE
reversing rotation direction skips one count

### ISSUE THREAD

**Issue by mkrzewic** [mathertel/RotaryEncoder#28]
in version 1.5.0 when reversing the direction of the knob the first getDirection returns 0 (norotation), needs one more tick to start reporting the proper direction. With 1.3.0 it works correctly.

**Comment by mathertel** [comment]
I will check...
What encode do you use (init parameters)

**Comment by mkrzewic** [comment]
just the simplest default: 
RotaryEncoder encoder(encoderPin1, encoderPin2);
(but i did try the non-default latching modes in 1.5.0, all have the same problem.)

i'm using interrupts to read, and get the direction like this:

auto dir = static_cast<int8_t>(encoder.getDirection());

**Comment by bluesky81** [comment]
Hello,
same problem in my project...
What is different from 1.3.0 to 1.5.0?
Should I use 1.3.0?

**Comment by mathertel** [comment]
I cannot easily reproduce. Please check that the inputs are both HIGH in the case of staying in a latch position.
See src\RotaryEncoder.cpp # 33.

If this is not the case then use another mode like LatchMode::FOUR0

In case this is not successful, please let me know how the input changes when slowly turning the knob.

// positions: [3] 1 0 2 [3] 1 0 2 [3]
// [3] is the positions where my rotary switch detends
// ==> right, count up
// <== left,  count down

**Comment by Phantasmagory** [comment]
Hello. I tried to do something like this:
`if (enc.isLeft()) i--;
  if (enc.isRight()) i++;`
and get this:
![Screenshot 2021-04-27 225659](https://user-images.githubusercontent.com/59103194/116307022-7b513600-a7ae-11eb-9dfb-03c15af33699.png)
maybe I'm not using the function correctly?

**Comment by Llaves** [comment]
I encountered the same issue with LatchMode::Four0 (the default). After examining the state sequence I determined my encoder latched on 3, not 0. Changing to LatchMode::Four3 made the problem disappear.

**Comment by mathertel** [comment]
Thanks for the hint.
