### ISSUE TITLE
add onChange callback? (Enhancement request)

### ISSUE THREAD

**Issue by Llaves** [mathertel/RotaryEncoder#31]
have you considered adding a callback that is invoked when the position changes? Kind of like your OneButton library where the click invokes a callback. 

Seems straightforward to callback from tick(), but maybe I'm missing some complication.

**Comment by Llaves** [comment]
I've implemented and tested this functionality and submitted a pull request.

**Comment by wotupfoo** [comment]
If you're doing interrupt driven ticks() you wouldn't be able to call a callback.  You'd need to use a semaphore.

**Comment by mathertel** [comment]
see discussion in pull request #32. closed here.
