### ISSUE TITLE
Working on mega 2560

### ISSUE THREAD

**Issue by dragoblaztr** [mathertel/RotaryEncoder#6]
What changes are required to make it work into a mega 2560, because it doesn't work as it is.

Regards

**Comment by acca84** [comment]
Hi try : 
RotaryEncoder encoder(A10, A11); // connect rotary to A10 and A11 instead of A2, A3
In the setup, use this two lines : 
PCICR |= (1 << PCIE2);    
PCMSK2 |= (1 << PCINT18) | (1 << PCINT19);

And replace the begining of the function by this  : 
ISR(PCINT2_vect) { 
...

**Comment by dragoblaztr** [comment]
If you don't mind, could you share information about mega2560 ports, pins and masks?

**Comment by acca84** [comment]
I don't have those infos

I made it work with Luck ! :D

**Comment by DjamTechnologies** [comment]
thank

**Comment by Ryder17z** [comment]
I just tested this library and it works fine on my mega 2560

**Comment by mathertel** [comment]
Thanks
