### ISSUE TITLE
I need to rotate two "notches" to get a change

### ISSUE THREAD

**Issue by M-Reimer** [mathertel/RotaryEncoder#8]
I have a encoder which needs to turned for two "notches" to get a change.

Is it possible to fix this somehow?

**Comment by mathertel** [comment]
This sounds odd. Any more details ?
Please verify that you rotary encoder outputs the signals in the right way.

**Comment by M-Reimer** [comment]
This actually is not "odd" but caused by differences between encoders.
There are "full step", "half step" and "quarter step" encoders available.
Seems like you only support the "full step" variant which does a full "bit cycle" for one "notch".
My encoder is a "half step" type which does half the bit changes a full step encoder would do.
That's why I have to move my encoder two "notches" to get a change with your library.

**Comment by mathertel** [comment]
ok, good to know.
I never had encoder of this kind around and I will write into the readme.
Thanks.

**Comment by M-Reimer** [comment]
I have a pull request ready for this. It actually is quite easy and non-intrusive to add this option. I need this for a pre-made hardware where I just want to change the firmware with something self-created. This hardware comes with this kind of "half step" encoder.

I really like the other features of your library and I think the Arduino library already has enough encoder support libraries, so I think it would be nice to have this built into your code.
