### ISSUE TITLE
INPUT_PULLUP

### ISSUE THREAD

**Issue by mrguen** [mathertel/RotaryEncoder#9]
Hello,

I tried to make it work on STM32F103C8T6 (with STM32duino support) . The old code does not work:
  pinMode(pin1, INPUT);
  digitalWrite(pin1, HIGH);   // turn on pullup resistor

And should be replaced by 

  pinMode(pin1, INPUT_PULLUP);

Same for pin2...

**Comment by mathertel** [comment]
Thank you !
Just pushed the changes.
